language: r
cache: packages
env:
  global:
  - secure: fqWe9XV/C7UDP+1QBjfhuZAyvw4bOQa5DMYQVlHM5nDaX+qA9J8azEp16j44pPaxTVqzRCXZXfjImtSsqxskkOL4Gwzu0im7b5Yxj9XavR30H0BtB0EKyxIvsPLOqycbM+qguhPHyoXSXRuFbktUsqESpqaVjzLj7PyFni0nE65KekCKiuTouSmCgHB83T2f8/aa9mPGQOuHC4BBkWEWymmWd3H7x58lV10FAnZbicxQJ+YSdx9BUFWsgZ6ffwr0UsHjArp5pJyXJxOmG/JkTIN7/l4eoorHKt/9X45Z9bI73ZVayUeU8RDeNGc3TMnxxbEnMFQHw3/ATjKm1kOcMVy/J5hBf8PP5qfj675vwrc18UhVSjLxJf+dtdhTFfHFzIOw2/UHnb1zTuafmylgtwTulFPPRElz5eX0lHFQc4YsL64olfDYv8hx0N3qxRkyWoHuXlpfcA8qOJr71Pkvg8qPkmKOSw2H386JqucjFX9xS5937UvF1vefGhS/ujWqyJ1MGS+MI4GZQ3hUIVFI5tBlzXBF1yaSDoPd2yDaYKIxxAVkSsKhi+n3QEthVM/bDqZgBYeuX+lGgmRABJnqYuGQcaPtPfhOM6/2UlZ3a7mdjH8Aq5juHAPPgYqNmlnsUkJyQM4bOoq18uv7KaK917DyTwv4n+FkZ64tYTIt7O8=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: false
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
r_github_packages:
- rstudio/bookdown
- mjskay/tidybayes
r_packages:
- tidyverse
- forcats
- broom
- ggstance
- Cairo
- effsize
- coin
- afex
- tidybayes
- import
- brms
- rstan
- import
- devtools
- MASS
